### ISSUE TITLE
error message [solved]

### ISSUE THREAD

**Issue by DoctorSubtilis** [jzeneto/pandoc-odt-filters#2]
Thank you for this effort. Today I tried to use your filter

     pandoc -t odt+smart --lua-filter odt-custom-styles.lua "Cattolicesimo romano e forma politica".md -o "Cattolicesimo romano e forma politica".odt

but I get this error message:

    Error running filter odt-custom-styles.lua: [string "odt-custom-styles.lua"]:7: unexpected symbol near '<'

and so: no conversion

**Comment by DoctorSubtilis** [comment]
Sorry: my mistake!  
Now the filter is working... but ...  
not saving my class/styles to odt: this is the md code

    <span class="symbol">&#58773;</span>
as well as  

    <span style="font-family: opensymbol; color: olive;">&#58773;</span>
not read as text but as symbol (without class)

**Comment by DoctorSubtilis** [comment]
**Solved**: now in Dolphin I have this command for md files:  

    sed -i -e 's@<span class="symbol">\&#58771;<\/span>@[\&#58771;]{custom-style="symbol"}@g' -e 's@<span class="symbol">\&#58772;<\/span>@[\&#58772;]{custom-style="symbol"}@g' -e 's@<span class="symbol">\&#58773;<\/span>@[\&#58773;]{custom-style="symbol"}@g' -e 's@<span class="symbol">\&#58774;<\/span>@[\&#58774;]{custom-style="symbol"}@g' %U && pandoc -t odt+smart --lua-filter odt-custom-styles.lua %U -o %u.odt --reference-doc="default.ott" && rename 's/md.odt/odt/g' *  
It works! Thank you!

**Comment by josineto** [comment]
Hi, @DoctorSubtilis, sorry for the extremely long silence. I'm glad that you found a way to make it work.

The `odt-custom-styles.lua` filter is designed to recognize styles marked as custom attributes in spans and divs in pure markdown (as apparently you perceived, judging by your own solution using `sed`). So:

```md
[a little span]{custom-style="symbol"}
```

is recognized, but

```html
<span class="symbol">a little span</span>
```

 doesn't. This is because Pandoc doesn't parse HTML spans as markdown spans, and so Lua filters can't manipulate them properly.

Also, custom *styles*, in this filter, refers to **ODT styles** (such as `Paragraph`, `Heading 1` and so on). CSS styles are a whole different type of styles.
